# 捕获异常
异常比较有趣的一个地方是可以对其进行处理，即**捕获异常**。为此，可以使用try/except语句。如有以下将输入的两个数相除的一个程序：
```
x = int(input(‘Enter the first number: ‘))
y = int(input(‘Enter the second number: ‘))
print(x/y)
```
这个程序运行正常，直到用户输入的第二个数是零：
```
Enter the first number:10
Enter the second number:0
Traceback (most recent call last):
  File “exceptions.py”, line 3, in ?
Print(x/y)
ZeroDivisionError: integer division or modulo by zero
```
为捕获这种异常并对错误进行处理，可以这样重写这个程序：
```
try :
    x = int(input(‘Enter the first number: ‘))
    y = int(input(‘Enter the second number: ‘))
    print(x/y)
except ZeroDivisionError:
    print(“The second number can’t be zero!”)
```
# 多个except子句
在上节程序中，如果输入一个非数字值，将会引发另一种异常：
```
Enter the first number:10
Enter the second number:”Hello, world!”
Traceback (most recent call last):
  File “exceptions.py”, line 4, in ?
Print(x/y)
TypeError: unsupported operand types(s) for /: ‘int’ and ‘str’
```
由于该程序中的except子句只捕获ZeroDivisionError异常，这种异常将被遗漏导致程序终止。为了同时捕获这种异常，可以在try/except语句中再添加一个except子句：
```
try :
    x = int(input(‘Enter the first number: ‘))
    y = int(input(‘Enter the second number: ‘))
    print(x/y)
except ZeroDivisionError:
    print(“The second number can’t be zero!”)
except TypeError:
    print(“That wasn’t a number, was it?”)
```
##### 需要注意的是，异常处理并不会导致代码混乱，而添加大量的if语句来检查各种可能的错误状况将导致代码的可读性极差。
